// <auto-generated />
using CardapioDigital.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CardapioDigital.Migrations.DishDb
{
    [DbContext(typeof(DishDbContext))]
    [Migration("20240129220306_AddDescriptionToDish")]
    partial class AddDescriptionToDish
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CardapioDigital.Models.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Ingredient1")
                        .HasColumnType("longtext");

                    b.Property<string>("Ingredient10")
                        .HasColumnType("longtext");

                    b.Property<string>("Ingredient2")
                        .HasColumnType("longtext");

                    b.Property<string>("Ingredient3")
                        .HasColumnType("longtext");

                    b.Property<string>("Ingredient4")
                        .HasColumnType("longtext");

                    b.Property<string>("Ingredient5")
                        .HasColumnType("longtext");

                    b.Property<string>("Ingredient6")
                        .HasColumnType("longtext");

                    b.Property<string>("Ingredient7")
                        .HasColumnType("longtext");

                    b.Property<string>("Ingredient8")
                        .HasColumnType("longtext");

                    b.Property<string>("Ingredient9")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Dishes");
                });
#pragma warning restore 612, 618
        }
    }
}
